# Gunakan image CentOS sebagai base image
FROM centos:latest

# Update sistem dan install Java
RUN yum update -y && \
    yum install -y java-11-openjdk-devel

# Buat direktori untuk aplikasi
RUN mkdir -p /opt/demo

# Salin jar file aplikasi ke dalam container
COPY target/demo-0.0.1-SNAPSHOT.jar /opt/demo/demo.jar

# Tentukan direktori kerja
WORKDIR /opt/demo

# Buat user non-root untuk menjalankan aplikasi
RUN useradd -ms /bin/bash appuser
USER appuser

# Ekspos port yang digunakan oleh aplikasi
EXPOSE 8080

# Jalankan aplikasi
ENTRYPOINT ["java", "-jar", "demo.jar"]
